const models = {
  users: Object.freeze({
    afk: -1,
    afkReason: '',
    exp: 0,
    health: 100,
    afkObj: {},
    level: 0,
    banned: false,
    ban_temporary: 0,
    ban_times: 0,
    premium: false,
    expired: 0,
    lastseen: 0,
    claim: 0,
    pasangan: "",
    guild: "",  // Guild pengguna
    guildRank: "",  // Rank dalam guild
    guildPoints: 0,  // Poin dalam guild
    guildContribution: 0,  // Kontribusi ke guild
    hit: 0,
    limit: 100,
    tiketcoin: 0,
    money: 0,
    transferHistory: [], // Riwayat transfer
    lastmerampok: 0,
    lastmembunuh: 0,
    lastAdventure: 0,
    lastpolisi: 0,
    lastclaim: 0,
    lastmining: 0,
    lastdungeon: 0,
    lastberkebon: 0,
    lastdagang: 0,
    lastberburu: 0,
    lastfishing: 0,
    lastHunter: 0, // Waktu terakhir berburu
    lastRaid: 0, // Waktu terakhir raid
    lastExpedition: 0, // Waktu terakhir ekspedisi
    gold: 0,
    diamond: 0,
    emerald: 0,
    fishingrod: 0,
    bait: 0,
    iron: 0,
    warning: 0,
    sword: 0,
    pickaxe: 0,
    armor: 0,
    lootBox: {
      common: 0,
      rare: 0,
      special: 0,
      mythic: 0,
      legends: 0,
      honor: 0
    },
    bibit: 0,
    pisang: 0,
    mangga: 0,
    anggur: 0,
    jeruk: 0,
    apel: 0,
    banteng: 0,
    harimau: 0,
    gajah: 0,
    kambing: 0,
    panda: 0,
    buaya: 0,
    kerbau: 0,
    sapi: 0,
    monyet: 0,      
    babihutan: 0,
    babi: 0,
    ayam: 0,
    bawal: 0,
    nila: 0,
    ikan: 0,
    lele: 0,
    udang: 0,
    paus: 0,
    kepiting: 0,
    kayu: 0,          
    batu: 0,           
    logam: 0,          
    copper: 0,         
    platinum: 0,      
    sapphire: 0,     
    ruby: 0,         
    amethyst: 0   
  }),
  groups: Object.freeze({
    activity: 0,
    antidelete: false,
    antilink: false,
    antivirtex: false,
    filter: false,
    left: true,
    localonly: false,
    mute: false,
    viewonce: false,
    autosticker: false,
    member: {},
    text_left: '',
    text_welcome: '',
    detect: false,
    demote: "",
    promote: "",
    welcome: true,
    expired: 0,
    stay: false
  }),
  chats: Object.freeze({
    chat: 0,
    lastchat: 0,
    lastseen: 0
  }),
  setting: Object.freeze({
    autodownload: true,
    groupmode: false,
    sk_pack: 'Sticker by',
    sk_author: '© Killua-Zoldyck',
    self: false,
    noprefix: false,
    multiprefix: true,
    prefix: ['.', '#', '!', '/'],
    toxic: ["ajg", "ajig", "anjas", "anjg", "anjim", "anjing", "anjrot", "anying", "asw", "autis", "babi", "bacod", "bacot", "bagong", "bajingan", "bangsad", "bangsat", "bastard", "bego", "bgsd", "biadab", "biadap", "bitch", "bngst", "bodoh", "bokep", "cocote", "coli", "colmek", "comli", "dajjal", "dancok", "dongo", "fuck", "gelay", "goblog", "goblok", "guoblog", "guoblok", "hairul", "henceut", "idiot", "itil", "jamet", "jancok", "jembut", "jingan", "kafir", "kanjut", "kanyut", "keparat", "kntl", "kontol", "lana", "loli", "lont", "lonte", "mancing", "meki", "memek", "ngentod", "ngentot", "ngewe", "ngocok", "ngtd", "njeng", "njing", "njinx", "oppai", "pantek", "pantek", "peler", "pepek", "pilat", "pler", "pornhub", "pucek", "puki", "pukimak", "redhub", "sange", "setan", "silit", "telaso", "tempek", "tete", "titit", "toket", "tolol", "tomlol", "tytyd", "wildan", "xnxx"],
    online: true,
    onlyprefix: '+',
    levelup: true,
    owners: ['6285133663664'],
    lastReset: new Date * 1,
    style: 4,
    backupTime: 0,
    backup: true,
    cover: 'https://img.hotimg.com/image0027b89a90dc3287.jpeg',
    link: 'https://whatsapp.com/channel/0029Vb3e1Ad6GcGCUntMjm2O'
  }),
  market: Object.freeze({
    BTC: 50294,
    ETH: 2500,
    DOGE: 1000,
    ADA: 5000,
    BNB: 1200,
    SOL: 3000,
    DOT: 5290,
    LTC: 19394
  })
};

module.exports = { models };
